from typing import Literal, Protocol

from stark.contracts import (
    StateType,
    StateTypeContravariant,
    TranslationType,
    TranslationTypeContravariant,
)


class CarrierStorage(Protocol[StateTypeContravariant, TranslationTypeContravariant]):
    def is_state(self, value: StateTypeContravariant) -> bool: ...
    def is_translation(self, value: TranslationTypeContravariant) -> bool: ...


class CarrierValidation(Protocol[StateType, TranslationType]):
    def validate_state(self, value: StateType) -> StateType: ...
    def validate_translation(self, value: TranslationType) -> TranslationType: ...
    def coerce_translation(self, value: TranslationType) -> TranslationType: ...


class CarrierAllocation(Protocol[StateType, TranslationType]):
    def zero_state(self) -> StateType: ...
    def zero_translation(self) -> TranslationType: ...
    def copy_state(self, value: StateType) -> StateType: ...
    def copy_translation(self, value: TranslationType) -> TranslationType: ...
    def allocate_translation(self) -> TranslationType: ...


class CarrierArithmetic(Protocol[StateType, TranslationType]):
    @property
    def preference(self) -> Literal["return", "into"]: ...

    def translate(self, state: StateType, step: float, derivative: TranslationType, result: StateType) -> StateType | None: ...
    def add(self, left: TranslationType, right: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def scale(self, factor: float, value: TranslationType, result: TranslationType) -> TranslationType | None: ...

    def combine2(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine3(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine4(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine5(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine6(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine7(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, a6: float, x6: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine8(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, a6: float, x6: TranslationType, a7: float, x7: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine9(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, a6: float, x6: TranslationType, a7: float, x7: TranslationType, a8: float, x8: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine10(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, a6: float, x6: TranslationType, a7: float, x7: TranslationType, a8: float, x8: TranslationType, a9: float, x9: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine11(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, a6: float, x6: TranslationType, a7: float, x7: TranslationType, a8: float, x8: TranslationType, a9: float, x9: TranslationType, a10: float, x10: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine12(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, a6: float, x6: TranslationType, a7: float, x7: TranslationType, a8: float, x8: TranslationType, a9: float, x9: TranslationType, a10: float, x10: TranslationType, a11: float, x11: TranslationType, result: TranslationType) -> TranslationType | None: ...

class CarrierNorm(Protocol[TranslationTypeContravariant]):
    def __call__(self, value: TranslationTypeContravariant) -> float: ...


class Carrier(Protocol[StateType, TranslationType]):
    @property
    def storage(self) -> CarrierStorage[StateType, TranslationType]: ...

    @property
    def validation(self) -> CarrierValidation[StateType, TranslationType]: ...

    @property
    def allocation(self) -> CarrierAllocation[StateType, TranslationType]: ...

    @property
    def arithmetic(self) -> CarrierArithmetic[StateType, TranslationType]: ...

    @property
    def norm(self) -> CarrierNorm[TranslationType]: ...
