"""Public method-stack catalogue.

`stark.methods` collects the pieces users combine into a `Method`: time
schemes, implicit resolvents, and linear inverse-action inverters. For a first
pass, most non-stiff problems should start with an explicit adaptive scheme
such as `SchemeCashKarp` or `SchemeTsitouras5`; stiff problems usually need an
implicit or IMEX scheme plus a resolvent and inverter.
"""

from stark.methods.inverters import (
    InverterConfiguration,
    InverterDense,
    InverterDescriptor,
    InverterKrylovArnoldi,
    InverterPreconditionerDiagonalInverse,
    InverterPreconditionerNone,
    InverterRelaxationJacobi,
    InverterRelaxationRichardson,
    InverterRelaxationLinearFixed,
    InverterRelaxationStencil,
    InverterRelaxationStencilUpdate,
)
from stark.methods.catalogue import METHOD_CATALOGUE
from stark.methods.method import Method, MethodError
from stark.methods.resolvents import (
    ResolventAnderson,
    ResolventBroyden,
    ResolventChord,
    ResolventConfiguration,
    ResolventCoupledNewton,
    ResolventCoupledPicard,
    ResolventDescriptor,
    ResolventError,
    ResolventNewton,
    ResolventPicard,
    ResolventVeryChord,
)
from stark.methods.schemes import (
    SchemeBDF2,
    SchemeBackwardEuler,
    SchemeBogackiShampine,
    SchemeCashKarp,
    SchemeCrankNicolson,
    SchemeCrouzeixDIRK3,
    SchemeDormandPrince,
    SchemeEuler,
    SchemeFehlberg45,
    SchemeGaussLegendre4,
    SchemeHeun,
    SchemeIMEXEuler,
    SchemeImplicitMidpoint,
    SchemeKennedyCarpenter32,
    SchemeKennedyCarpenter43_6,
    SchemeKennedyCarpenter43_7,
    SchemeKennedyCarpenter54,
    SchemeKennedyCarpenter54b,
    SchemeKutta3,
    SchemeKvaerno3,
    SchemeKvaerno4,
    SchemeKvaerno5,
    SchemeLobattoIIIC4,
    SchemeMidpoint,
    SchemeRK4,
    SchemeRK38,
    SchemeRadauIIA5,
    SchemeRalston,
    SchemeSDIRK21,
    SchemeSSPRK33,
    SchemeTsitouras5,
)

__all__ = (
    "InverterConfiguration",
    "InverterDense",
    "InverterDescriptor",
    "InverterKrylovArnoldi",
    "InverterPreconditionerDiagonalInverse",
    "InverterPreconditionerNone",
    "InverterRelaxationJacobi",
    "InverterRelaxationRichardson",
    "InverterRelaxationLinearFixed",
    "InverterRelaxationStencil",
    "InverterRelaxationStencilUpdate",
    "Method",
    "METHOD_CATALOGUE",
    "MethodError",
    "ResolventAnderson",
    "ResolventBroyden",
    "ResolventChord",
    "ResolventConfiguration",
    "ResolventCoupledNewton",
    "ResolventCoupledPicard",
    "ResolventDescriptor",
    "ResolventError",
    "ResolventNewton",
    "ResolventPicard",
    "ResolventVeryChord",
    "SchemeBDF2",
    "SchemeBackwardEuler",
    "SchemeBogackiShampine",
    "SchemeCashKarp",
    "SchemeCrankNicolson",
    "SchemeCrouzeixDIRK3",
    "SchemeDormandPrince",
    "SchemeEuler",
    "SchemeFehlberg45",
    "SchemeGaussLegendre4",
    "SchemeHeun",
    "SchemeIMEXEuler",
    "SchemeImplicitMidpoint",
    "SchemeKennedyCarpenter32",
    "SchemeKennedyCarpenter43_6",
    "SchemeKennedyCarpenter43_7",
    "SchemeKennedyCarpenter54",
    "SchemeKennedyCarpenter54b",
    "SchemeKutta3",
    "SchemeKvaerno3",
    "SchemeKvaerno4",
    "SchemeKvaerno5",
    "SchemeLobattoIIIC4",
    "SchemeMidpoint",
    "SchemeRK4",
    "SchemeRK38",
    "SchemeRadauIIA5",
    "SchemeRalston",
    "SchemeSDIRK21",
    "SchemeSSPRK33",
    "SchemeTsitouras5",
)
