"""Protocols for the carrier interface used by the newer object model.

Carriers describe how STARK should store, validate, allocate, combine, and
measure a user's state/translation pair. They are intended as the documented
interface layer above lower-level optimized kernels: users can start from these
small protocols and only drop into custom kernels where performance needs it.
"""

from __future__ import annotations

from typing import Literal, Protocol

from stark.core.contracts.problem.state import (
    StateType,
    StateTypeContravariant,
)
from stark.core.contracts.problem.translation import (
    TranslationType,
    TranslationTypeContravariant,
)


class CarrierStorageLike(Protocol[StateTypeContravariant, TranslationTypeContravariant]):
    """Recognize state and translation values for one carrier family."""

    def is_state(self, value: StateTypeContravariant) -> bool: ...
    def is_translation(self, value: TranslationTypeContravariant) -> bool: ...


class CarrierValidationLike(Protocol[StateType, TranslationType]):
    """Validate or coerce objects at public carrier boundaries."""

    def validate_state(self, value: StateType) -> StateType: ...
    def validate_translation(self, value: TranslationType) -> TranslationType: ...
    def coerce_translation(self, value: TranslationType) -> TranslationType: ...


class CarrierAllocationLike(Protocol[StateType, TranslationType]):
    """Allocate and copy state/translation objects for reusable workspaces."""

    def zero_state(self) -> StateType: ...
    def zero_translation(self) -> TranslationType: ...
    def copy_state(self, value: StateType) -> StateType: ...
    def copy_translation(self, value: TranslationType) -> TranslationType: ...
    def allocate_translation(self) -> TranslationType: ...


class CarrierArithmeticLike(Protocol[StateType, TranslationType]):
    """Perform carrier-aware state and translation algebra.

    `preference` declares whether implementations prefer return-style algebra
    or into-style mutation. All combination methods keep output/result last,
    matching the package-wide optimized-kernel convention.
    """

    @property
    def preference(self) -> Literal["return", "into"]: ...

    def translate(self, state: StateType, step: float, dynamics: TranslationType, result: StateType) -> StateType | None: ...
    def add(self, left: TranslationType, right: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def scale(self, factor: float, value: TranslationType, result: TranslationType) -> TranslationType | None: ...

    def combine2(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine3(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine4(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine5(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine6(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine7(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, a6: float, x6: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine8(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, a6: float, x6: TranslationType, a7: float, x7: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine9(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, a6: float, x6: TranslationType, a7: float, x7: TranslationType, a8: float, x8: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine10(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, a6: float, x6: TranslationType, a7: float, x7: TranslationType, a8: float, x8: TranslationType, a9: float, x9: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine11(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, a6: float, x6: TranslationType, a7: float, x7: TranslationType, a8: float, x8: TranslationType, a9: float, x9: TranslationType, a10: float, x10: TranslationType, result: TranslationType) -> TranslationType | None: ...
    def combine12(self, a0: float, x0: TranslationType, a1: float, x1: TranslationType, a2: float, x2: TranslationType, a3: float, x3: TranslationType, a4: float, x4: TranslationType, a5: float, x5: TranslationType, a6: float, x6: TranslationType, a7: float, x7: TranslationType, a8: float, x8: TranslationType, a9: float, x9: TranslationType, a10: float, x10: TranslationType, a11: float, x11: TranslationType, result: TranslationType) -> TranslationType | None: ...

class CarrierNormLike(Protocol[TranslationTypeContravariant]):
    """Measure translation size for error control and convergence tests."""

    def __call__(self, value: TranslationTypeContravariant) -> float: ...


class CarrierLike(Protocol[StateType, TranslationType]):
    """Complete carrier bundle for one state/translation representation."""

    @property
    def storage(self) -> CarrierStorageLike[StateType, TranslationType]: ...

    @property
    def validation(self) -> CarrierValidationLike[StateType, TranslationType]: ...

    @property
    def allocation(self) -> CarrierAllocationLike[StateType, TranslationType]: ...

    @property
    def arithmetic(self) -> CarrierArithmeticLike[StateType, TranslationType]: ...

    @property
    def norm(self) -> CarrierNormLike[TranslationType]: ...
